### ISSUE TITLE
 `typeof' not defined

### ISSUE THREAD

**Issue by mathzzz** [JaHIY/simple_http_server#1]
[root@localhost ~]# awk 'BEGIN{print typeof(xx)}'
awk: cmd. line:1: fatal: function `typeof' not defined
[root@localhost ~]# awk -V
GNU Awk 4.0.2

**Comment by JaHIY** [comment]
I thtnk your awk is too old to run it.
This is my development environment for developing this project.
````bash
> awk -V
GNU Awk 5.1.1, API: 3.1 (GNU MPFR 4.1.0-p13, GNU MP 6.2.1)
````
